import { Heart, Users, UserCircle, Briefcase, Smile, Star } from 'lucide-react';

export const RELATIONSHIP_TYPES_MAP = {
  romantic: {
    label: 'Romantic Partner',
    icon: Heart,
    color: 'text-rose-500',
    bg: 'bg-rose-50',
    border: 'border-rose-200',
    egoLabel: 'Put Partner First',
    gratitudeLabel: 'Grateful For',
    memberLabel: 'Partner',
    membersLabel: 'Partners',
  },
  siblings: {
    label: 'Siblings',
    icon: Users,
    color: 'text-amber-500',
    bg: 'bg-amber-50',
    border: 'border-amber-200',
    egoLabel: 'Put Sibling First',
    gratitudeLabel: 'Grateful For',
    memberLabel: 'Sibling',
    membersLabel: 'Siblings',
  },
  parent_child: {
    label: 'Parent & Adult Child',
    icon: UserCircle,
    color: 'text-emerald-500',
    bg: 'bg-emerald-50',
    border: 'border-emerald-200',
    egoLabel: 'Put Them First',
    gratitudeLabel: 'Grateful For',
    memberLabel: 'Family Member',
    membersLabel: 'Family',
  },
  family: {
    label: 'Family Group',
    icon: Users,
    color: 'text-violet-500',
    bg: 'bg-violet-50',
    border: 'border-violet-200',
    egoLabel: 'Put Family First',
    gratitudeLabel: 'Grateful For',
    memberLabel: 'Family Member',
    membersLabel: 'Family Members',
  },
  friendship: {
    label: 'Friendship',
    icon: Smile,
    color: 'text-sky-500',
    bg: 'bg-sky-50',
    border: 'border-sky-200',
    egoLabel: 'Put Friend First',
    gratitudeLabel: 'Grateful For',
    memberLabel: 'Friend',
    membersLabel: 'Friends',
  },
  business: {
    label: 'Business',
    icon: Briefcase,
    color: 'text-stone-600',
    bg: 'bg-stone-100',
    border: 'border-stone-200',
    egoLabel: 'Put Team First',
    gratitudeLabel: 'Grateful For',
    memberLabel: 'Partner',
    membersLabel: 'Partners',
  },
  other: {
    label: 'Relationship',
    icon: Star,
    color: 'text-indigo-500',
    bg: 'bg-indigo-50',
    border: 'border-indigo-200',
    egoLabel: 'Put Them First',
    gratitudeLabel: 'Grateful For',
    memberLabel: 'Member',
    membersLabel: 'Members',
  },
};

export function getRelTypeInfo(type) {
  return RELATIONSHIP_TYPES_MAP[type] || RELATIONSHIP_TYPES_MAP.other;
}